### ISSUE TITLE
Write some best practices guidance for creating components

### ISSUE THREAD

**Issue by rgbkrk** [nteract/vdom#11]
Within `vdom`, the best way (that I can think of right now) to create new elements is to create functions that return elements:

```python
from vdom import h, p, div
def happiness(level=90):
  smiley = "😃"
  percent = level / 100.
    
  if(percent < 0.25):
    smiley = "☹️"
  elif(percent < 0.50):
    smiley = "😐"
  elif(percent < 0.75):
    smiley = "😀"

    
  return p([
      'Happiness ', smiley, h('br'), h('meter', level, min="0", low=25, high=75, optimum=90, max=100, value=level)
  ])
# Usage:

happiness()

div([
  happiness(10),
  happiness(32),
  happiness(65),
  happiness(80)
])
```

Example in nteract:

![screen shot 2017-09-25 at 11 49 15 am](https://user-images.githubusercontent.com/836375/30825369-93461922-a1e7-11e7-803c-04bd20e7fb2d.png)

**Comment by ellisonbg** [comment]
Without JSX (let's not write JSX for python), this is exactly what I think makes sense. We were doing this with phosphor's vdom library before we got it working with JSX.
