### ISSUE TITLE
Provide SVG Helpers

### ISSUE THREAD

**Issue by ellisonbg** [nteract/vdom#16]
Wondering if it makes sense to create helpers for SVG elements? There are quite a few:

https://developer.mozilla.org/en-US/docs/Web/SVG/Element

Maybe a new `svg.py` file for those?

**Comment by rgbkrk** [comment]
Yeah I think that makes sense. Would we want it at `vdom.helpers.svg`, making helpers a subfolder/module, and ensuring the current tags surface on `vdom.helpers`?

**Comment by rgbkrk** [comment]
For potential contributors, here's what to do / how to tackle it:

* Create svg.py in `vdom/`
* Create the components for SVG like this:

```python
circle = createComponent('circle')
```

* Create all the SVG components using MDN's [SVG Element](https://developer.mozilla.org/en-US/docs/Web/SVG/Element) reference

**Comment by rgbkrk** [comment]
Done in #29.
