### ISSUE TITLE
Write JSON Schema for the VDOM Spec

### ISSUE THREAD

**Issue by rgbkrk** [nteract/vdom#3]
Write [JSON Schema](http://json-schema.org/), like Jupyter does for nbformat.

To accompany [the spec doc](https://github.com/nteract/vdom/blob/master/docs/spec.md).

**Comment by sara-02** [comment]
@rgbkrk I would like to take this up.

**Comment by rgbkrk** [comment]
Awesome! Have at it, let us know if you have questions.

**Comment by willingc** [comment]
@sara-02 Fantastic. Like Kyle mentions, we'er happy to answer questions. :sunny:

**Comment by sara-02** [comment]
@rgbkrk @willingc Thanks. I will come back with questions when I code this up. :)

**Comment by sara-02** [comment]
@rgbkrk I was going through the codebase and found a schema validation function [here](https://github.com/nteract/vdom/blob/master/vdom/core.py#L14). 
Why do we need another validator?

**Comment by rgbkrk** [comment]
The validator doesn't do anything yet because we don't have a schema to run through it. It's ready for you!

**Comment by rgbkrk** [comment]
Next steps to take:

Create `vdom.v1.schema.json` (see [`nbformat.v4.schema.json`](https://github.com/jupyter/nbformat/blob/master/nbformat/v4/nbformat.v4.schema.json) as an example). It's probably going to start off like:

```json
{
    "$schema": "http://json-schema.org/draft-04/schema#",
    "description": "VDOM v1.0 JSON Schema.",
    "type": "object",
    "additionalProperties": false,
    "required": ["tagName", "children", "attributes"],
    ...
    "definitions": {
      "vdomEl": {
        ...
```

After you've got the file written, you'll want to read it in and set it up as the default schema in the `toJSON` function.

**Comment by mpacer** [comment]
Hi @sara-02 for some further context, I had the understanding that you wanted to develop the json schema itself, not the functionality for validating the schema. I specifically wrote that PR in order to make it easier for you to pass your schema while you were developing it. I had meant to post

> I’m going work on a backwards compatible change to the API of `toJSON`  so you can test your schema more easily

But I forgot to actually submit the comment. 

Hopefully that helps give you context!

**Comment by Madhu94** [comment]
@sara-02 Are you working on this now ?

**Comment by sara-02** [comment]
@Madhu94 Sorry, I did not get time to work on this :/

**Comment by mpacer** [comment]
@sara-02 will you have the time to work on this? 

We can help! 

For example, I'll make a dumb stand-in that doesn't really do much to validate other than hook up an actual json schema to the validation mechanism used to create the objects. 

That way all you would need to do is to improve upon the existing schema!

**Comment by Madhu94** [comment]
@rgbkrk I guess this is good to close then ?

**Comment by rgbkrk** [comment]
Nope, we still need a schema. All that @mpacer added was a starter schema file, we don't have the proper definition here yet.

**Comment by Madhu94** [comment]
> All that @mpacer added was a starter schema file, we don't have the proper definition here yet.
Oh I should have checked the diff.
@sara-02 I'm taking this up if you don't mind.

**Comment by willingc** [comment]
@Madhu94 Thanks for your enthusiasm and desire to contribute.

Let's give @sara-02 48 hours to respond if she would like to continue the work she has done or have you pick up the rest of the issue. Thanks!

**Comment by Madhu94** [comment]
@willingc Sure, I'll wait for a few days. @sara-02 Let me know if I can pick this up.

**Comment by sara-02** [comment]
@Madhu94 sorry for the delay, please take it forward.

**Comment by willingc** [comment]
Thanks @sara-02. Looking forward to contributing in the future :sunflower:

**Comment by Madhu94** [comment]
I've been trying some variations of what I've posted below, but I cannot make vdomEl and vdomNode reference each other.  Is it even possible to make a "recursive" schema ? Or was the validation only meant for the top level and the recursion to be done in code ?

```

{
  "type": "object",
  "$schema": "http://json-schema.org/draft-04/schema#",
  "additionalProperties": false,
  "required": ["tagName", "children", "attributes"],
  "properties": {
    "tagName": {
      "type": "string" 
    },
    "children": {
      "type": "array",
      "items": {"$ref": "#/definitions/vdomNode"}
    },
    "attributes": {
      "type": "object"   
    },
    "key": {
      "oneOf": [{"type": "number"}, {"type": "string"}, {"type": "null"}]
    }
  },
  "definitions": {
    "vdomEl": {
      "type": "object",
      "required": ["tagName", "children", "attributes"],
      "properties": {
        "tagName": {
          "type": "string" 
        },
        "children": {
          "type": "array",
          "items": {"$ref": "#/definitions/vdomNode"}
        },
        "attributes": {
          "type": "object"   
        },
        "key": {
          "oneOf": [{"type": "number"}, {"type": "string"}, {"type": "null"}]
        }
      }
    },
    "vdomNode": {
      "oneOf": [
        {"type": "object"}, // Trying to add a reference to vdomEl here !
        {"type": "array", "items": {"$ref": "#/definitions/vdomNode"}},
        {"type": "null"}
      ]
    }  
  }
}
```
