### ISSUE TITLE
Void tags must _not_ have children

### ISSUE THREAD

**Issue by rgbkrk** [nteract/vdom#39]
We should enforce void tags not having children at the python level (though we can also check it at the frontend level). Otherwise, [React will report a _major_ error about void tag children](https://reactjs.org/docs/error-decoder.html?invariant=137&args[]=input&args[]=) (not a warning), followed by bombing the entire app (assuming no `componentDidCatch` implemented). Known tags we should check for this on, in order of likely importance (estimated usage):

* [x] `input`
* [x] `img`
* [x] `br`
* [x] `hr`
* [x] `link`
* [x] `meta`
* [x] `param`
* [x] `base`
* [x] `area`
* [x] `keygen`
* [x] `command`
* [x] `source`

**Comment by mpacer** [comment]
What is the equivalent of having "void tag children" inside the notion of python?

**Comment by rgbkrk** [comment]
children for each of these tags should each be None

**Comment by rgbkrk** [comment]
Closed by #40, #41.
