### ISSUE TITLE
Unexpected Literal html Output

### ISSUE THREAD

**Issue by rdodev** [nteract/vdom#47]
Hey folks,

Taking `vdom` for a spin on Jupyter notebook. Trying the example in your docs produces unexpected literal html output as shows in attached image below.

OS: OS X (High Sierra)
Python: 2.7.x
vdom: 0.5 (from pip)
![screen shot 2017-12-27 at 11 53 45 am](https://user-images.githubusercontent.com/1234335/34387582-04d8a844-eafd-11e7-9106-c8b3caa68fd6.png)

**Comment by rdodev** [comment]
When wrapped around `display` also produces same output:

![screen shot 2017-12-27 at 11 58 07 am](https://user-images.githubusercontent.com/1234335/34387636-4a91e7d8-eafd-11e7-9a46-ef1679319dbb.png)

**Comment by Madhu94** [comment]
@rdodev This isn't supported in the notebook yet (https://github.com/jupyter/notebook/pull/2840). You can try this out in nteract

**Comment by rdodev** [comment]
@Madhu94 Ahh well, that explains it =)

**Comment by rgbkrk** [comment]
JupyterLab supports it as well. 😄

**Comment by rdodev** [comment]
Oh nice. Was having a hard time without tab-complete on nteract :) This will help.

**Comment by rgbkrk** [comment]
nteract uses typeahead, the other way to trigger completion is with ctrl-space. 😄

**Comment by yuvipanda** [comment]
I'm gonna close this now!

#43 should help get vdom on older notebook interfaces.
