### ISSUE TITLE
Broken images

### ISSUE THREAD

**Issue by chenjiandongx** [nteract/vdom#61]
In [design-patterns.md](https://github.com/nteract/vdom/blob/master/docs/design-patterns.md), all the images broken
![image](https://user-images.githubusercontent.com/19553554/40153275-9f6f8724-59bb-11e8-8cf1-7fa30b0171c9.png)

And it seems not a vaild img url

![image](https://user-images.githubusercontent.com/19553554/40153312-dcdb4d5a-59bb-11e8-8c57-824712d98afa.png)

**Comment by rgbkrk** [comment]
Oh yeah, they sure are. We should re-generate those.
