### ISSUE TITLE
Example notebooks are broken

### ISSUE THREAD

**Issue by mpacer** [nteract/vdom#67]
Right now, our `_html_repr_` is not handling a couple of our features:

- [x] Boolean key-value pairs (all values are treated as strings meaning you cannot define `<video controls><source src='…'></video> ` as opposed to `<video ><source src='…'></video> `) 
- [x] DOM style css keys don't work in style attribute blocks (inline style info needs to be defined with css-style names)
- [ ] Updating existing display objects does not work since we changed VDOM objects to be immutable; this breaks the last examples in [exploring-elements.ipynb](https://github.com/nteract/vdom/blob/master/example-notebooks/exploring-elements.ipynb)
    - But note that we do have updated progressbars in [custom-progress-bars.ipynb](https://github.com/nteract/vdom/blob/master/example-notebooks/custom-progress-bars.ipynb)

I've got a PR to fix the first two but the last one is more of a design decision on how we want to support updated displays of vdom objects.

@rgbkrk @yuvipanda

**Comment by willingc** [comment]
#68 fixes the first two items. Third item moved to #83
