### ISSUE TITLE
fyi: Cloned functionality for widgets

### ISSUE THREAD

**Issue by AaronWatters** [nteract/vdom#74]
Hi folks.  I'm not sure that this is the right place to put this, but I was inspired by `vdom` to add similar functionality to the `jp_doodle` jupyter widgets package.  Please have a look here for a demo:

https://github.com/AaronWatters/jp_doodle/blob/master/notebooks/misc/wdom%20demo.ipynb

I will add additional documentation in the fullness of time.

Thanks!  -- Aaron Watters

**Comment by rgbkrk** [comment]
Love it.

cc @gnestor

**Comment by gnestor** [comment]
@AaronWatters This is awesome! We are working on adding event handler suppor-endt to vdom. It's currently implemented on master and I am working on implementing it on the front (@nteract/transform-vdom which is used by nteract and JupyterLab). We are trying to keep the API as similar to React's as possible. You can read more about it in [the spec](https://github.com/nteract/vdom/blob/master/docs/event-spec.md) and I have a demo of it working in JupyterLab in [this branch](https://github.com/gnestor/jupyter-renderers/tree/vdom-experimental/packages/vdom-experimental-extension) (you can press the "launch binder" to play with it but it looks like it's not working at the moment).

**Comment by AaronWatters** [comment]
Nice.

The `jp_doodle` version supports events (and anything else available using jQuery or jQueryUI) out of the box and has a lot of other capabilities like generic Python callbacks from Javascript and the reverse.  It does not support some of the other use cases you have in mind like serializing to stand alone HTML.  You can also run the example using Binder here:

https://mybinder.org/v2/gh/AaronWatters/jp_doodle/master

The WDOM(...) is a proxy widget. The proxy widget tutorial describes what that is and how it works here:

https://github.com/AaronWatters/jp_proxy_widget/blob/master/notebooks/Tutorial.ipynb

FYI.

I'm not sure what to do with this issue.  I guess I'll let it rest for a bit and come back to close it in a few
days.  Let me know if there is a more appropriate place for comments/threads like this

**Comment by AaronWatters** [comment]
I'm closing/thread this comment because it is really not in issue. :)
