### ISSUE TITLE
vdom in google-collab?

### ISSUE THREAD

**Issue by rcox771** [nteract/vdom#77]
I just gave it a shot and found that it didn't work out of the box. All I get is an empty div for the example. Is there a quick fix?

![image](https://user-images.githubusercontent.com/13604961/49095540-b003e080-f236-11e8-9456-88f81c899345.png)

 I could see vdom getting adopted much more across the academic/mooc communities out there if this was a thing. There are already some out there that use widget interfaces to do simple dataset interaction, ml model prediction, etc. but vdom seems like it could do wonders.

**Comment by rgbkrk** [comment]
You'll want to let the colab folks know over in https://github.com/googlecolab/backend-container or something.

cc @craigcitro

**Comment by craigcitro** [comment]
Thanks @rgbkrk!

https://github.com/googlecolab/colabtools/issues is the place to report (aka `Help` -> `Report a bug`).

**Comment by rcox771** [comment]
Will do, thanks @craigcitro @rgbkrk
