### ISSUE TITLE
Is version 0.6 stable?

### ISSUE THREAD

**Issue by KrishnaKumarHariprasannan** [nteract/vdom#87]
Hi,

https://github.com/nteract/vdom/releases/latest is still pointing to release 0.5. Is it safe to use 0.6 or should one wait for it to be tagged with the latest tag?

**Comment by captainsafia** [comment]
Hello @KrishnaKumarHariprasannan!

Thanks for opening this issue! It is safe to use 0.6. It appears that something went wrong in the tagging of the 0.6 release and it is not populating correctly in GitHub. We can resolve this in the 0.7 release.
